### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ojflore** [ojflore/vetmove#79]
Make sure the following is pushed to github, if not already done:

Finalize API
Finalize Business Model Canvas
Update Use Cases

**mySQL Documentation**
     Screenshot of database design
     Data Model?
     mySQL Workbench file

**Comment by jessb1620** [comment]
what do you mean by MySQL documentation?

**Comment by ojflore** [comment]
I still need more clarification for Dr. Voortman. Can you take this for action and ask him what he needs?

**Comment by jessb1620** [comment]
Yep, I'll ask him now!

**Comment by ojflore** [comment]
Thank you!

**Comment by jessb1620** [comment]
No problem!
